# Cloud Build pipeline for Terraform (plan+apply) with security scanning
# Uses SA impersonation inside the Terraform provider; no JSON keys used.

substitutions:
  _ENV_DIR: "."
  _TF_STATE_BUCKET: "tfstate-terraform-488518"
  _TF_STATE_PREFIX: "network/dev"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/gcloud
  id: Show Versions
  entrypoint: bash
  args:
    - -chdir=envs/dev
    - -lc
    - |
      gcloud --version
      terraform -version || true

- name: hashicorp/terraform:1.6.6
  id: fmt-validate
  entrypoint: sh
  args:
    - -c
    - |
    - -chdir=envs/dev
      terraform fmt -check
      terraform init -input=false         -backend-config="bucket=${_TF_STATE_BUCKET}"         -backend-config="prefix=${_TF_STATE_PREFIX}"
      terraform validate

- name: gcr.io/cloud-builders/gcloud
  id: tfsec
  entrypoint: bash
  args:
    - -lc
    - |
      curl -sSL https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      tfsec --soft-fail ${_ENV_DIR}

- name: hashicorp/terraform:1.6.6
  id: plan
  entrypoint: sh
  args:
    - -c
    - |
    - -chdir=envs/dev
      terraform plan -input=false -out=tfplan

- name: hashicorp/terraform:1.6.6
  id: apply
  entrypoint: sh
  args:
    - -c
    - |
    - -chdir=envs/dev
      # cd ${_ENV_DIR}
      terraform apply -input=false -auto-approve tfplan
