# Cloud Build pipeline for Terraform (plan+apply) with security scanning
# Files are located in the root directory.

substitutions:
  _ENV_DIR: "."
  _TF_STATE_BUCKET: "tfstate-terraform-488518"
  _TF_STATE_PREFIX: "network/dev"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Show Versions for debugging
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Show Versions'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud --version
        terraform -version

  # 2. Security Scan (tfsec)
  # Using a pre-built image is more reliable than installing via curl on mobile/cloud environments.
  - name: 'aquasec/tfsec:v1.28'
    id: 'Security Scan'
    args: ['${_ENV_DIR}']

  # 3. Terraform Format, Init, and Validate
  - name: 'hashicorp/terraform:1.6.6'
    id: 'Initialize and Validate'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd ${_ENV_DIR} || exit
        terraform fmt -check
        terraform init -input=false \
          -backend-config="bucket=${_TF_STATE_BUCKET}" \
          -backend-config="prefix=${_TF_STATE_PREFIX}"
        terraform validate

  # 4. Terraform Plan
  - name: 'hashicorp/terraform:1.6.6'
    id: 'Plan'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd ${_ENV_DIR} || exit
        terraform plan -input=false -out=tfplan

  # 5. Terraform Apply
  - name: 'hashicorp/terraform:1.6.6'
    id: 'Apply'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd ${_ENV_DIR} || exit
        terraform apply -input=false -auto-approve tfplan
